### ISSUE TITLE
Contour gallery doesn't work with ad-blockers turned on

### ISSUE THREAD

**Issue by narenranjit** [forio/contour#234] opened 2016-06-06 19:46 UTC
http://forio.com/contour/gallery.html#/chart/bar/bar-styled for e.g.,

We're using fancy google analytics custom events, and not accounting for the possibility that google analytics may be blocked entirely.

We're not _actually_ analyzing google analytics in that level of detail anyway, so may be simpler just to remove if wrapping everything in a `if(!analytics)return` is too much work.

**Comment by mmrj** [comment] 2016-06-06 21:39
closing as duplicate of https://issues.forio.com/browse/FNM-112 

(we're using GitHub for Contour issues, but if it's specific to the Contour gallery/website as opposed to Contour library/docs, that goes in the jira project. sorry for the confusion.)

**Closed by mmrj** 2016-06-06 21:39 UTC
